# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: CarnegieMellonUniversity.Alice3
PackageVersion: 3.9.0.2
InstallerType: exe
InstallerSwitches:
  Silent: -q
  SilentWithProgress: -q
ReleaseDate: 2025-06-11
AppsAndFeaturesEntries:
- DisplayName: Alice 3 3.8.0.0+build.1046
  DisplayVersion: 3.8.0.0+build.1046
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/TheAliceProject/alice3/releases/download/3.9.0.2/alice3_windows-x64_installer_3_9_0_2+build_1224.exe
  InstallerSha256: 488ED8391930B7BAE8CAD2781E684945DEF7062E8E05D09061A04A879930D310
ManifestType: installer
ManifestVersion: 1.10.0
