# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: HearthSim.HearthstoneDeckTracker
PackageVersion: 1.44.15
PackageLocale: en-US
Publisher: HearthSim
PublisherUrl: https://hearthsim.net/
Author: HearthSim
PackageName: Hearthstone Deck Tracker
PackageUrl: https://hsreplay.net/downloads
License: Proprietary
LicenseUrl: https://hearthsim.net/legal/terms-of-service.html
Copyright: Copyright © HearthSim. All Rights Reserved.
CopyrightUrl: https://hearthsim.net/legal/terms-of-service.html
ShortDescription: A deck tracker and deck manager for Hearthstone on Windows
Tags:
- deck-tracker
- game
- hearthstone
ManifestType: defaultLocale
ManifestVersion: 1.10.0
