# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: ThePandemoniumInstitute.BloodontheClocktowerOnline
PackageVersion: 3.43.0
PackageLocale: en-US
Publisher: Steffen Baumgart
PublisherUrl: https://bloodontheclocktower.com/
PublisherSupportUrl: https://github.com/ThePandemoniumInstitute/botc-release/issues
PrivacyUrl: https://bloodontheclocktower.com/privacy-policy
PackageName: Blood on the Clocktower Online
PackageUrl: https://github.com/ThePandemoniumInstitute/botc-release
License: Proprietary
LicenseUrl: https://bloodontheclocktower.com/terms-of-use
Copyright: Copyright © 2024 Steffen Baumgart
ShortDescription: Blood on the Clocktower Online
Moniker: clocktower
Tags:
- app
- binaries
- botc
- clocktower
- download
ReleaseNotes: |-
  - 🚀 added Deus ex Fiasco
  - 🌟 improved general security by preventing account creation with disposable email addresses and phone numbers
ReleaseNotesUrl: https://github.com/ThePandemoniumInstitute/botc-release/releases/tag/v3.43.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
