# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: mentebinaria.retoolkit
PackageVersion: '2023.10'
InstallerLocale: en-US
InstallerType: inno
Scope: user
InstallerSwitches:
  Silent: /VERYSILENT /NORESTART /COMPONENTS="*android *autoit *calculators *cobaltstrike *debuggers *decompilers *delphi *dotnet *elf *go *hexeditors *java *ole *network *pdf *pe *peresourceeditors *processinspection *programming *signature *systeminformation *unpacking *utilities !network\nmap"
  SilentWithProgress: /SILENT /NORESTART /COMPONENTS="*android *autoit *calculators *cobaltstrike *debuggers *decompilers *delphi *dotnet *elf *go *hexeditors *java *ole *network *pdf *pe *peresourceeditors *processinspection *programming *signature *systeminformation *unpacking *utilities !network\nmap"
UpgradeBehavior: install
Commands:
- CobaltStrikeScan
- DisView
- OfficeMalScanner
- RTFScan
- bazzar
- capa
- d2j-dex2jar
- de4dot
- floss
- hollows_hunter
- manw
- pe-sieve
- redress
- upx
- vt
- winapiexec
ProductCode: '{BB46345D-F5E9-408E-AA39-64A5EDD92E30}_is1'
ReleaseDate: 2023-10-31
AppsAndFeaturesEntries:
- ProductCode: '{BB46345D-F5E9-408E-AA39-64A5EDD92E30}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\retoolkit'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/mentebinaria/retoolkit/releases/download/2023.10/retoolkit_2023.10_setup.exe
  InstallerSha256: 955DF4EF2E43167EAABA02F231CC45CCF18907AFA1C37B52429F1D1A70A5967C
ManifestType: installer
ManifestVersion: 1.9.0
