# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: D4koon.WhatsappTray
PackageVersion: 1.9.0
InstallerType: inno
ReleaseDate: 2022-01-15
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/D4koon/WhatsappTray/releases/download/v1.9.0/WhatsappTrayV1.9.0.0.exe
  InstallerSha256: 6535FA20F12FD21C0ABD104E5594D4F0AE82528D4274D3470D9C1FBB3C403A18
ManifestType: installer
ManifestVersion: 1.6.0
