# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Exploitox.WebRadio
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: Exploitox
PublisherUrl: https://exploitox.de/
PublisherSupportUrl: https://exploitox.de/kontakt
PrivacyUrl: https://exploitox.de/datenschutzerklaerung/
Author: valnoxy
PackageName: WebRadio
PackageUrl: https://github.com/valnoxy/WebRadio
License: GPL-3.0
LicenseUrl: https://github.com/valnoxy/WebRadio/blob/HEAD/LICENSE.md
Copyright: Copyright (c) 2018 - 2023 Exploitox. All rights reserved.
ShortDescription: Simple Web Radio / Stream player
Description: WebRadio is a small application for playing web radio channels or streams.
Moniker: radio
Tags:
- music
- stream
- web
ReleaseNotes: |-
  🔔 About WebRadio
  WebRadio is a small application for playing web radio channels or streams.- Play different radio streams and save them to the favorites list
  - Discord integration, so your friends can see what music you are listening too
  This is the first release of WebRadio.MicrosoftStore
ReleaseNotesUrl: https://github.com/valnoxy/WebRadio/releases/tag/v1.0.0
ManifestType: defaultLocale
ManifestVersion: 1.6.0
