# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: pluveto.Upgit
PackageVersion: 0.2.25
InstallerType: portable
Commands:
- upgit
ReleaseDate: 2024-07-11
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/pluveto/upgit/releases/download/v0.2.25/upgit_win_386.exe
  InstallerSha256: 6C9B2752ECBF754FF6CEAC3584B1EACCA6930581AA4A67A39DCCA47F6A3074A7
- Architecture: x64
  InstallerUrl: https://github.com/pluveto/upgit/releases/download/v0.2.25/upgit_win_amd64.exe
  InstallerSha256: 5D091EA77C69B0145AE80BA9DB1C359F9A5730977247BBC8130BAD5F57F5DE78
- Architecture: arm
  InstallerUrl: https://github.com/pluveto/upgit/releases/download/v0.2.25/upgit_win_arm.exe
  InstallerSha256: 4E1BF7210B5CE3F33A17A48796DA3C2BF9B91EF770FDD7848043273E57A0C965
- Architecture: arm64
  InstallerUrl: https://github.com/pluveto/upgit/releases/download/v0.2.25/upgit_win_arm64.exe
  InstallerSha256: 1847D84768E20EB256A7494C8AFFCA98F5D9AB27758B33785654FE0FD382561E
ManifestType: installer
ManifestVersion: 1.9.0
