# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.9.0.schema.json

PackageIdentifier: pluveto.Upgit
PackageVersion: 0.2.25
PackageLocale: zh-CN
Publisher: Zijing Zhang
PublisherUrl: https://www.less-bug.com/
PublisherSupportUrl: https://github.com/pluveto/upgit/issues
Author: Zijing Zhang
PackageName: Upgit
PackageUrl: https://github.com/pluveto/upgit
License: MIT
LicenseUrl: https://github.com/pluveto/upgit/blob/main/LICENSE
Copyright: Copyright (c) 2023 pluveto
ShortDescription: 另一款支持剪贴板的上传工具，可与 Typora、Snipaste、VSCode 搭配使用。
Description: Upgit 可以快捷地将文件上传到 GitHub 仓库并得到其直链。简洁跨平台，不常驻内存。
Tags:
- snipaste
- typora
- vscode
- 上传
- 上传器
- 图像
- 图片
ManifestType: locale
ManifestVersion: 1.9.0
