# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: huanghongxun.HelloMinecraftLauncher
PackageVersion: 3.5.6.242
PackageLocale: zh-CN
Publisher: huanghongxun
PublisherUrl: https://www.huangyuhui.net/
PublisherSupportUrl: https://afdian.net/@huanghongxun
PrivacyUrl: https://hmcl.huangyuhui.net/about/
Author: Yellow Fish
PackageName: Hello Minecraft! Launcher
PackageUrl: https://hmcl.huangyuhui.net/
License: GPL-3.0
LicenseUrl: https://github.com/HMCL-dev/HMCL/blob/HEAD/LICENSE
Copyright: Copyright (C) 2021 huangyuhui
ShortDescription: HMCL 是一个免费、开源的 Minecraft 启动器，允许玩家方便快捷地安装、管理、运行游戏。
Moniker: hmcl
Tags:
- hello-minecraft-launcher
- hmcl
- minecraft
- minecraft-curseforge
- minecraft-launcher
ReleaseNotes: |-
  The full changelogs can be found on the website: https://docs.hmcl.net/changelog/dev.html
  Notice: changelogs are written in Chinese.| File Name | SHA-256 Checksum |
  | ---  | --- |
  | HMCL-3.5.6.242.exe | a3bfc3b19e08c4fb388e4c88531c8ab48ae04de92ee4e7a13a0fffe05e2beee3 |
  | HMCL-3.5.6.242.jar | 2a8b9cabe5cbd68d9aef96ca143002483791d94cc5d70f9c86ef176e86e852dd |
  | HMCL-3.5.6.242.sh  | 986433321390ccc5eb9544e3db655b47a79b73249280e43fea6ce1c076cdae38 |
ReleaseNotesUrl: https://github.com/HMCL-dev/HMCL/releases/tag/v3.5.6.242
InstallationNotes: 使用指令 hmcl 启动
ManifestType: defaultLocale
ManifestVersion: 1.6.0
