# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: mar10.pyftpsync
PackageVersion: 4.0.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
