# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: xssnick.tonutils-storage
PackageVersion: 1.1.3
InstallerType: portable
UpgradeBehavior: install
ReleaseDate: 2025-07-15
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/xssnick/tonutils-storage/releases/download/v1.1.3/tonutils-storage-x64.exe
  InstallerSha256: E8AD3A251267A3237362D8ED6C2108F3AD5DFEA2AD5998E19D228788A23E64C8
ManifestType: installer
ManifestVersion: 1.10.0
