# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: AdaLang.Alire
PackageVersion: 2.1.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: install --confirm-command --root "C:\Program Files\Alire"
  SilentWithProgress: install --confirm-command --root "C:\Program Files\Alire"
  InstallLocation: --root "<INSTALLPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 2
  ReturnResponse: installInProgress
- InstallerReturnCode: 3
  ReturnResponse: cancelledByUser
UpgradeBehavior: deny
ReleaseDate: 2025-03-04
RequireExplicitUpgrade: true
AppsAndFeaturesEntries:
- DisplayVersion: Windows-d9b80158-20241009
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/alire-project/alire/releases/download/v2.1.0/alr-2.1.0-installer-x86_64-windows.exe
  InstallerSha256: 180FB3D96C5A2AF9E0219DFAFF683E71B8B917DEEB381F67DCC5423E1E51D0CA
ManifestType: installer
ManifestVersion: 1.9.0
