# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Anki.Anki
PackageVersion: 25.07.2
PackageLocale: en-US
Publisher: Anki
PublisherUrl: https://github.com/ankitects/anki
PublisherSupportUrl: https://github.com/ankitects/anki/issues
Author: Ankitects
PackageName: Anki
PackageUrl: https://apps.ankiweb.net/
License: AGPL-3.0-or-later
LicenseUrl: https://github.com/ankitects/anki/blob/HEAD/LICENSE
CopyrightUrl: https://raw.githubusercontent.com/ankitects/anki/master/LICENSE
ShortDescription: Powerful and intelligent flash cards.
Description: |-
  Anki is a program which makes remembering things easy.
  Because it's a lot more efficient than traditional study methods, you can either greatly decrease your time spent studying, or greatly increase the amount you learn.
  Anyone who needs to remember things in their daily life can benefit from Anki.
  Since it is content-agnostic and supports images, audio, videos and scientific markup (via LaTeX), the possibilities are endless.
Moniker: anki
Tags:
- education
- flashcard
- learn
ReleaseNotes: |-
  What's Changed
  - The first run of the launcher now installs the latest version automatically.
  - When choosing a specific version, recent versions are shown.
  - Feat/Confirmation box for save options to preset by @Luc-Mcgrady in #4172
  - Respect env var UV_BINARY with OFFLINE_BUILD being set by @AlexBocken in #4170
  - [A11Y] FIX: revert button is visible for screenreaders by @GithubAnon0000 in #4174
  - Try unix terminals in roughly most specific to least specific. by @Grinkers in #4177
  - Feat/Replace easy day table with display:grid by @Luc-Mcgrady in #4179
  - Fix/Help modal appears behind simulator modal by @Luc-Mcgrady in #4171
  - Aqt wheel: fix unintended inclusion of qt/aqt/data by @pHlt7 in #4180
  Full Changelog: 25.07.1...25.07.2
ReleaseNotesUrl: https://github.com/ankitects/anki/releases/tag/25.07.2
Documentations:
- DocumentLabel: Anki Manual
  DocumentUrl: https://docs.ankiweb.net/
- DocumentLabel: FAQ
  DocumentUrl: https://faqs.ankiweb.net/
ManifestType: defaultLocale
ManifestVersion: 1.10.0
