# Created with Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: BleuBleu.FamiStudio
PackageVersion: 4.1.2
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: msi
NestedInstallerFiles:
- RelativeFilePath: Setup.msi
ProductCode: '{CF536749-47F3-454D-AA31-2BBFC6CF9DCB}'
ReleaseDate: 2023-08-14
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/BleuBleu/FamiStudio/releases/download/4.1.2/FamiStudio412-WinInstaller.zip
  InstallerSha256: 50D542FD90006F20318334FC36FE54B25DA46E6EA50E4AF864DE92BAB0B5A7E1
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.5.0
