# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Intel.PresentMon
PackageVersion: 2.3.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ProductCode: '{FEDF9434-5212-4132-81D7-225D3E7CAF27}'
ReleaseDate: 2025-06-10
AppsAndFeaturesEntries:
- ProductCode: '{FEDF9434-5212-4132-81D7-225D3E7CAF27}'
  UpgradeCode: '{CD0D489E-0FE7-452D-90D9-F94F3F5FF410}'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Intel\PresentMon'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GameTechDev/PresentMon/releases/download/v2.3.1/PresentMon-v2.3.1.msi
  InstallerSha256: 763B341F6D591A31C8FD870011FB4F798F4ADA0D5BD9F4B8286DC364EEA78090
ManifestType: installer
ManifestVersion: 1.10.0
