# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: PowerClouds.CertoNiuchacz
PackageVersion: 2.0.1
DefaultLocale: pl-pl
ManifestType: version
ManifestVersion: 1.6.0
