# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: YutakaSawada.MultiPar
PackageVersion: 1.3.3.4
PackageLocale: en-US
Publisher: Yutaka Sawada
PublisherUrl: https://hp.vector.co.jp/authors/VA021385/
PublisherSupportUrl: https://github.com/Yutaka-Sawada/MultiPar/issues
PackageName: MultiPar
PackageUrl: https://github.com/Yutaka-Sawada/MultiPar/
License: Proprietary
LicenseUrl: https://hp.vector.co.jp/authors/VA021385/archive.htm
Copyright: Copyright 2008-2024 Yutaka Sawada
ShortDescription: MultiPar is a Parchive compliant data protection and recovery program.
Moniker: multipar
Tags:
- par2
- parchive
- recovery
ReleaseNotes: |-
  This is a minor update version. As I announced ago, Windows Vista was removed from supported OS from this version. If you are using MultiPar on Windows Vista PC, please use old versions. If there is no serious problem in this version, next version may be the last of v1.3.3 tree.
  Korean language is available newly. Thanks gemble for translation.
  I added some optional feature for rare usage or test manually. For details, refer Command_GUI.txt and Command_par2j.txt in help folder of MultiPar.
  My web-pages on vector.co.jp will disapper at 2024 December 20. Thanks Vector to support MultiPar for long time. I use this GitHub page for MultiPar announcement.
  [ Changes from 1.3.3.3 to 1.3.3.4 ]
  Installer update
  - Korean language is available at installation.
  GUI update
  - New
    - Korean UI DLL is included.
    - It's possible to add options for par2j on MultiPar.ini file.
  - Change
    - Link of Vector's author page is removed. Use GitHub's MultiPar page.
  [ Hash value ]
  MultiPar1334.zip
  MD5: 27E7EB8CD03F65D219E7B59E870C0CF3
  SHA1: 523BBA26FA851BB320962196F7197978801568B3
  MultiPar1334_setup.exe
  MD5: 4F1F3EEDF79EBFBEB63078F3F0528CC7
  SHA1: F9AA66DF5E0CDA0D2F99FE27B2FA8667BE079BB2
  To install under "Program Files" or "Program Files (x86)" directory, you must select "Install for all users" at the first dialog.
  Old versions and source code packages are available at GitHub or OneDrive.
ReleaseNotesUrl: https://github.com/Yutaka-Sawada/MultiPar/releases/tag/v1.3.3.4
ManifestType: defaultLocale
ManifestVersion: 1.9.0
