# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: YutakaSawada.MultiPar
PackageVersion: 1.3.3.4
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallerSwitches:
  Custom: /ALLUSERS
ProductCode: '{AAFC96BF-C615-4D77-9A55-C692A7B26FC5}_is1'
ReleaseDate: 2024-11-30
AppsAndFeaturesEntries:
- ProductCode: '{AAFC96BF-C615-4D77-9A55-C692A7B26FC5}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Yutaka-Sawada/MultiPar/releases/download/v1.3.3.4/MultiPar1334_setup.exe
  InstallerSha256: 7D7BFC583BD9C1141209642461292C1D525E2F132B47E8D22887EB57843673C1
ManifestType: installer
ManifestVersion: 1.9.0
