# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: mgth.LittleBigMouse
PackageVersion: '5.1'
InstallerType: nullsoft
ReleaseDate: 2024-03-10
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/mgth/LittleBigMouse/releases/download/v5.1/LittleBigMouse-5.1.0.0.exe
  InstallerSha256: 1A157B0A6355DFB2C6548E38E27454FD09F0C48E8FEF19963A93546AEE2F7AF9
ManifestType: installer
ManifestVersion: 1.6.0
