# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: benaclejames.VRCFaceTracking
PackageVersion: 5.2.3.0
PackageLocale: en-US
Publisher: benaclejames
PublisherUrl: https://github.com/benaclejames
PublisherSupportUrl: https://github.com/benaclejames/VRCFaceTracking/issues
PackageName: VRCFaceTracking
PackageUrl: https://github.com/benaclejames/VRCFaceTracking
License: Apache-2.0
LicenseUrl: https://github.com/benaclejames/VRCFaceTracking/blob/HEAD/LICENSE
ShortDescription: VRChat OSC App to allow AV3 Avatars to interact with eye and lip tracking runtimes
Tags:
- eyetracking
- facetracking
- vrcft
- vrchat
ReleaseNotes: |-
  These release notes will be updated shortly
  What's Changed
  - change m/s to msgs/sec in OSC section in main page by @kusomaigo in #190
  - Combo parameters vol 1 by @RantiMess in #193
  - Fix incomplete code for handling debug camera streams by @hyblocker in #181
  - Parameter name consistency fix by @RantiMess in #195
  New Contributors
  - @hyblocker made their first contribution in #181
  Full Changelog: 5.1.1.0...5.2.3.0
  Full Changelog: 5.2.3.0...5.2.3.0
ReleaseNotesUrl: https://github.com/benaclejames/VRCFaceTracking/releases/tag/5.2.3.0
ManifestType: defaultLocale
ManifestVersion: 1.9.0
