# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: benaclejames.VRCFaceTracking
PackageVersion: 5.2.3.0
Platform:
- Windows.Desktop
- Windows.Universal
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
UpgradeBehavior: install
PackageFamilyName: 96ba052f-0948-44d8-86c4-a0212e4ae047_p4c7kbkq180dc
Capabilities:
- internetClientServer
RestrictedCapabilities:
- runFullTrust
ReleaseDate: 2024-04-12
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\WindowsApps\96ba052f-0948-44d8-86c4-a0212e4ae047_5.2.3.0_x64__p4c7kbkq180dc'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/benaclejames/VRCFaceTracking/releases/download/5.2.3.0/VRCFaceTracking_5.2.3.0_x64.msix
  InstallerSha256: 9D5952420AB9FD3C390CB8C42845652FD3F1211F9750F4C744B5259D5FB2C48D
  SignatureSha256: 029A81EEB89D9FFC73374EB10B4FC54BB34B2CC9E0FD078BF4414A7F1527B8CE
ManifestType: installer
ManifestVersion: 1.9.0
