# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: RestApia.RestApiaDesktop
PackageVersion: 0.9.3
PackageLocale: en-US
Publisher: RestApia
PublisherUrl: https://github.com/RestApia
PublisherSupportUrl: https://github.com/RestApia/RestApia.Community/issues
PackageName: RestApia
PackageUrl: https://github.com/RestApia/RestApia.Community
License: Proprietary
Copyright: Copyright © 2024 RestApia
ShortDescription: Rest API client to test HTTP endpoints
Description: A REST API client designed for testing HTTP endpoints, offering a clean and code-friendly approach to defining request parameters. Ideal for developers who prefer a hands-on, code-centric workflow.
Tags:
- rest, api, testing, http
ReleaseNotes: |-
  What's New
  - Extended Early Access Program (EAP) date until the end of the year.
  - Various minor enhancements for improved performance and stability.
ReleaseNotesUrl: https://github.com/RestApia/Releases.Win.Stable/releases/tag/v0.9.3-win-stable
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/RestApia/Releases.Win.Stable/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
