# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: GaetanSencie.ContabilidadAnual
PackageVersion: 1.9.0.0
InstallerLocale: es
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silentWithProgress
FileExtensions:
- dat
- exe
- md
ProductCode: '{29D81E73-481B-4BAA-87D9-C3C253C2D435}}_is1'
ReleaseDate: 2025-05-04
AppsAndFeaturesEntries:
- DisplayName: Contabilidad Anual Simple
  ProductCode: '{29D81E73-481B-4BAA-87D9-C3C253C2D435}}_is1'
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Contabilidad Anual Simple'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/STENS66/Contabilidad-anual/releases/download/V1.9.0.0/Contabilidad.Anual.Simple.V1-9.exe
  InstallerSha256: F304CB53A6ED0C01109C85E13F4006FAACB0F862244A1AACAB68D312F90C97F7
ManifestType: installer
ManifestVersion: 1.10.0
