# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Intel.PresentMon.Console
PackageVersion: 2.3.1
InstallerType: portable
Commands:
- presentmon
ReleaseDate: 2025-06-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GameTechDev/PresentMon/releases/download/v2.3.1/PresentMon-2.3.1-x64.exe
  InstallerSha256: 364E5D98D4D134BD54DD25C22ED2CA2F4883F8BC3ED6502BEE0C151E3436D30C
ManifestType: installer
ManifestVersion: 1.10.0
