# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: GaetanSencie.SimpleAnnualAccounting
PackageVersion: 2.0.0.0
InstallerLocale: fr-FR
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
FileExtensions:
- dat
- exe
- md
ProductCode: '{29D81E73-481B-4BAA-87D9-C3C253C2D435}}_is1'
ReleaseDate: 2025-07-10
AppsAndFeaturesEntries:
- ProductCode: '{29D81E73-481B-4BAA-87D9-C3C253C2D435}}_is1'
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Simple Annual Accounting'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/STENS66/Comptabilite_annuelle/releases/download/V2.0.0.0/Simple.Annual.Accounting.Setup.exe
  InstallerSha256: 4094BB149BFB72F218F7CB75C3F3A0A76E46A9C2F52C993673499AB7C77B67FD
ManifestType: installer
ManifestVersion: 1.10.0
