# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: huanghongxun.HelloMinecraftLauncher
PackageVersion: 3.5.7.244
PackageLocale: zh-CN
Publisher: huanghongxun
PublisherUrl: https://www.huangyuhui.net/
PublisherSupportUrl: https://afdian.net/@huanghongxun
PrivacyUrl: https://hmcl.huangyuhui.net/about/
Author: Yellow Fish
PackageName: Hello Minecraft! Launcher
PackageUrl: https://hmcl.huangyuhui.net/
License: GPL-3.0
LicenseUrl: https://github.com/HMCL-dev/HMCL/blob/HEAD/LICENSE
Copyright: Copyright (C) 2021 huangyuhui
ShortDescription: HMCL 是一个免费、开源的 Minecraft 启动器，允许玩家方便快捷地安装、管理、运行游戏。
Moniker: hmcl
Tags:
- hello-minecraft-launcher
- hmcl
- minecraft
- minecraft-curseforge
- minecraft-launcher
ReleaseNotes: |-
  The full changelogs can be found on the website: https://docs.hmcl.net/changelog/dev.html
  Notice: changelogs are written in Chinese.| File Name | SHA-256 Checksum |
  | ---  | --- |
  | HMCL-3.5.7.244.exe | eae8749576a0e2903bc0aa9eca109823c154e81bdb50600850d19b77d96ff155 |
  | HMCL-3.5.7.244.jar | 40269748b7fd5a99b7d52b371ca31ad914b2981185c59dbf2fed028d5b2e00c0 |
  | HMCL-3.5.7.244.sh  | 07a661d8b9e989f45e1ccff671b3d44387fdf7cd1a11fd676026d79d963732b4 |
ReleaseNotesUrl: https://github.com/HMCL-dev/HMCL/releases/tag/v3.5.7.244
InstallationNotes: 使用指令 hmcl 启动
ManifestType: defaultLocale
ManifestVersion: 1.6.0
