# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: JamesCJ60.Universalx86TuningUtility
PackageVersion: 2.5.3
PackageLocale: en-US
Publisher: JamesCJ60
PublisherUrl: https://github.com/JamesCJ60
PublisherSupportUrl: https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/issues
PackageName: Universal x86 Tuning Utility
PackageUrl: https://github.com/JamesCJ60/Universal-x86-Tuning-Utility
License: GPL-3.0
LicenseUrl: https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/blob/HEAD/LICENSE
ShortDescription: Unlock the full potential of your Intel/AMD based device
Moniker: uxtu
Tags:
- amd
- intel
- laptop
- overclock
- ryzen
- undervolt
- undervolting
ReleaseNotes: |-
  Changes made:
  - Various bug fixes and improvements!
  Reminder: The Intel backend for this application will be updated in a future release
  Downloads:
  Windows
  Installer Download
  Portable Download
ReleaseNotesUrl: https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/releases/tag/2.5.3
ManifestType: defaultLocale
ManifestVersion: 1.10.0
