# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.6.0.schema.json

PackageIdentifier: mscststs.LANService
PackageVersion: 0.0.5
PackageLocale: zh-CN
Publisher: mscststs
PublisherUrl: https://github.com/mscststs
PublisherSupportUrl: https://github.com/mscststs/LANService/issues
Author: mscststs
PackageName: LANService
PackageUrl: https://github.com/mscststs/LANService
License: MIT
LicenseUrl: https://github.com/mscststs/LANService/blob/main/LICENSE
Copyright: Copyright (c) 2022 mscststs
ShortDescription: 一个客户端，使局域网内的设备可以通过网页控制计算机
Tags:
- 局域网
- 远程控制
ReleaseNotes: |-
  现已支持：鼠标控制
  像使用触控板一样使用触控区域吧
ReleaseNotesUrl: https://github.com/mscststs/LANService/releases/tag/v0.0.5
ManifestType: locale
ManifestVersion: 1.6.0
